Dependency, Java and gradle version update
sysgears/grain pull request #22
Opened 2017-01-20 18:06 UTC by altavir

Jetbrain annotations instead of obsolete `javax`. 
'application.properties' made optional.

2017-01-20 18:24 UTC, larixer requested changes

2017-01-20 18:24 UTC, vlasenko commented on build.gradle
> +//    dependencies { classpath 'org.eclipse.jgit:org.eclipse.jgit:3.1.0.201310021548-r' }
Please remove this line, if dependency is unused inside `build.gradle`

2017-01-20 18:24 UTC, vlasenko commented on build.gradle
> +    javaCompatibilityVersion = 1.8
Why do you increase requirement for minimum Java version to 1.8?

2017-01-20 18:24 UTC, vlasenko commented on src/main/groovy/com/sysgears/grain/highlight/CachedHighlighter.groovy
> +import org.jetbrains.annotations.Nullable
Why to use JetBrains annotations instead of Javax, they look vendor-specific. Why do you say, that javax annotations are obsolete?

2017-01-20 18:24 UTC, vlasenko commented on src/main/groovy/com/sysgears/grain/init/CmdlineParser.groovy
> +            if (!currentVersion.isBackwardCompatible(themeVersion)) {
I think we don't need to validate Grain version at all, I think these check need to be just removed

2017-01-21 05:11 UTC, altavir commented on build.gradle
> +    javaCompatibilityVersion = 1.8
Why not? Java 7 is not supported anymore. On the other hand JDK 8 has a lot of very convenient features that are useful even in groovy.
For current code it does not matter though.

P. S. Hey people, Java 9 is coming! Java 7 is 6 years old.

2017-01-21 06:27 UTC, vlasenko commented on build.gradle
> +    javaCompatibilityVersion = 1.8
Yes, the point is for current code we don't use features of Java 8, so its better to support both as it doesn't "cost" as anything.

2025-04-28 12:59 UTC, larixer commented
Closing PR as stale at this point.

2025-04-28 12:59 UTC, closed without merging